# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:            Stephanie Millar
tagline:          
url:              http://stephaniemillar.github.io/
paginate:         3
baseurl:          /
author:
  name:           Stephanie Millar
  url:            https://twitter.com/stephiemillar
  email:          stephanienmillar@gmail.com

gems:
  - jekyll-sitemap