# Permalinks
permalink:            pretty
relative_permalinks:  true

# Setup
title:                Why Not a Rhino?
tagline:          
url:                  http://www.whynotarhino.com/
paginate:             4
baseurl:              http://www.whynotarhino.com/
author:
  name:               Stephanie Millar
  url:                https://twitter.com/stephiemillar
  email:              stephanienmillar@gmail.com

markdown:             kramdown

kramdown:
  smart_quotes:       ["apos", "apos", "quot", "quot"]

gems:
  - jekyll-sitemap