# Permalinks
permalink:        	pretty
relative_permalinks: true

# Setup
title:            Stephanie Millar
tagline:          Smart rhino
url:              http://stephaniemillar.github.io/
paginate:         1
baseurl:          /
author:
  name:           Stephanie Millar
  url:            https://twitter.com/stephiemillar
  email:          stephanienmillar@gmail.com